### ISSUE TITLE
manuscript doesn't render

### ISSUE THREAD

**Issue by andreashandel** [katiemwells/connor-katie-MADA-project#1]
I cannot render your manuscript, because you are using setwd()
Please fix. See here for information:
https://andreashandel.github.io/MADAcourse/Data_Analysis_Structure.html

Once it is fixed, I'll take another look and provide feedback as suitable.

**Comment by katiemwells** [comment]
I made some edits that hopefully fixed this issue. Let me know if this works!

**Comment by andreashandel** [comment]
still not working, this fails:
resulttable=readRDS("../../results/summarytable.rds")

**Comment by katiemwells** [comment]
Sorry, there was some lingering code from your template document that was messing with the render. Should work now.
